apiVersion: v1
kind: Secret
metadata:
    name: payments-secrets
    namespace: shop-system
    labels:
        app.kubernetes.io/name: shop-system
        app.kubernetes.io/component: payments
        app.kubernetes.io/instance: local
type: Opaque
data:
    DB_USER: "c2hvcF91c2Vy"
    DB_PASSWORD: "c2hvcF9wYXNzd29yZA=="

