apiVersion: apps/v1
kind: Deployment
metadata:
    name: mysql
    namespace: shop-system
    labels:
        app.kubernetes.io/name: shop-system
        app.kubernetes.io/component: mysql
        app.kubernetes.io/instance: local
spec:
    selector: { matchLabels: { app.kubernetes.io/component: mysql } }
    replicas: 1
    template:
        metadata:
            labels:
                app.kubernetes.io/name: shop-system
                app.kubernetes.io/component: mysql
                app.kubernetes.io/instance: local
        spec:
            containers:
                - name: mysql
                  image: mysql:9.1
                  env:
                      - name: MYSQL_ROOT_PASSWORD
                        value: root_password
                      - name: MYSQL_DATABASE
                        value: shop_system_auth
                      - name: MYSQL_USER
                        value: shop_user
                      - name: MYSQL_PASSWORD
                        value: shop_password
                  volumeMounts:
                      - mountPath: /var/lib/mysql
                        name: mysql-storage
                      - mountPath: /docker-entrypoint-initdb.d
                        name: mysql-init-script
                  livenessProbe:
                      exec:
                          command:
                              - mysqladmin
                              - ping
                              - -h
                              - localhost
                      initialDelaySeconds: 30
                      periodSeconds: 10
                      timeoutSeconds: 5
                  readinessProbe:
                      exec:
                          command:
                              - mysqladmin
                              - ping
                              - -h
                              - localhost
                      initialDelaySeconds: 10
                      periodSeconds: 5
                      timeoutSeconds: 3
            volumes:
                - name: mysql-storage
                  persistentVolumeClaim:
                      claimName: mysql-pvc
                - name: mysql-init-script
                  configMap:
                      name: mysql-init-script
