apiVersion: apps/v1
kind: Deployment
metadata:
    name: mailhog
    namespace: shop-system
    labels:
        app.kubernetes.io/name: shop-system
        app.kubernetes.io/component: mailhog
        app.kubernetes.io/instance: local
spec:
    replicas: 1
    selector: { matchLabels: { app.kubernetes.io/component: mailhog } }
    template:
        metadata:
            labels:
                app.kubernetes.io/name: shop-system
                app.kubernetes.io/component: mailhog
                app.kubernetes.io/instance: local
        spec:
            containers:
                - name: mailhog
                  image: mailhog/mailhog
                  ports:
                      - containerPort: 8025
                        name: ui
                      - containerPort: 1025
                        name: smtp
                  livenessProbe:
                      tcpSocket:
                          port: 8025
                      initialDelaySeconds: 10
                      periodSeconds: 10
                  readinessProbe:
                      tcpSocket:
                          port: 8025
                      initialDelaySeconds: 5
                      periodSeconds: 5
