controllers:
    resource: ../src/UI/Controller
    type: attribute

kernel:
    resource: ../src/Kernel.php
    type: attribute

api_login_check:
    path: /api/v1/login

app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

#app_catch_all:
#    path: /{path}
#    controller: App\Controller\EntryController::index
#    requirements:
#        path: .*
