apiVersion: v1
kind: ConfigMap
metadata:
    name: frontend-config
    namespace: shop-system
    labels:
        app.kubernetes.io/name: shop-system
        app.kubernetes.io/component: frontend
        app.kubernetes.io/instance: local
data:
    API_URL: "http://192.168.49.2:30081/api/v1"
    PAYMENTS_URL: "http://192.168.49.2:30082/api/v1"
    NEXT_PUBLIC_API_URL: "http://192.168.49.2:30081/api/v1"
    NEXT_PUBLIC_PAYMENTS_URL: "http://192.168.49.2:30082/api/v1"
    NODE_ENV: "development"
