apiVersion: v1
kind: Secret
metadata:
    name: frontend-secrets
    namespace: shop-system
    labels:
        app.kubernetes.io/name: shop-system
        app.kubernetes.io/component: frontend
        app.kubernetes.io/instance: local
type: Opaque
data:
