apiVersion: v1
kind: Service
metadata:
    name: frontend
    namespace: shop-system
    labels:
        app.kubernetes.io/name: shop-system
        app.kubernetes.io/component: frontend
        app.kubernetes.io/instance: local
spec:
    type: NodePort
    selector:
        app.kubernetes.io/component: frontend
    ports:
        - name: http
          protocol: TCP
          port: 3000
          targetPort: 3000
          nodePort: 30080

