apiVersion: apps/v1
kind: Deployment
metadata:
    name: redis
    namespace: shop-system
    labels:
        app.kubernetes.io/name: shop-system
        app.kubernetes.io/component: redis
        app.kubernetes.io/instance: local
spec:
    replicas: 1
    selector: { matchLabels: { app.kubernetes.io/component: redis } }
    template:
        metadata:
            labels:
                app.kubernetes.io/name: shop-system
                app.kubernetes.io/component: redis
                app.kubernetes.io/instance: local
        spec:
            containers:
                - name: redis
                  image: redis:7.4
                  ports: [{ containerPort: 6379 }]
                  volumeMounts:
                      - mountPath: /data
                        name: redis-storage
                  livenessProbe:
                      exec:
                          command:
                              - redis-cli
                              - ping
                      initialDelaySeconds: 15
                      periodSeconds: 10
                      timeoutSeconds: 3
                  readinessProbe:
                      exec:
                          command:
                              - redis-cli
                              - ping
                      initialDelaySeconds: 5
                      periodSeconds: 5
                      timeoutSeconds: 3
            volumes:
                - name: redis-storage
                  persistentVolumeClaim:
                      claimName: redis-pvc
