apiVersion: v1
kind: ConfigMap
metadata:
    name: backend-config
    namespace: shop-system
    labels:
        app.kubernetes.io/name: shop-system
        app.kubernetes.io/component: backend
        app.kubernetes.io/instance: local
data:
    APP_ENV: "prod"
    COMPOSE_PROJECT_NAME: "shop_system"
    MYSQL_HOST: "mysql"
    MYSQL_PORT: "3306"
    AUTH_MYSQL_DATABASE: "shop_system_auth"
    COMMERCE_MYSQL_DATABASE: "shop_system_commerce"
    REDIS_URL: "redis://redis:6379/0"
    REDIS_APP_PREFIX: "shop_system_local"
    MESSENGER_TRANSPORT_DSN: "amqp://guest:guest@rabbitmq:5672/%2f/messages"
    JWT_TOKEN_TTL: "3600"
    MAILER_DSN: "smtp://mailhog:1025"
    CORS_ALLOW_ORIGIN: "^https?://(localhost|127\\.0\\.0\\.1|192\\.168\\.49\\.2)(:[0-9]+)?$"
    ELASTICSEARCH_HOST: "elasticsearch"
    ELASTICSEARCH_PORT: "9200"
    ELASTICSEARCH_SCHEME: "http"
    PAYMENTS_SERVICE_URL: "http://payments:8080"
