apiVersion: apps/v1
kind: Deployment
metadata:
    name: backend
    namespace: shop-system
    labels:
        app.kubernetes.io/name: shop-system
        app.kubernetes.io/component: backend
        app.kubernetes.io/instance: local
spec:
    replicas: 1
    selector:
        matchLabels:
            app.kubernetes.io/component: backend
    template:
        metadata:
            labels:
                app.kubernetes.io/name: shop-system
                app.kubernetes.io/component: backend
                app.kubernetes.io/instance: local
        spec:
            initContainers:
                - name: setup-code
                  image: maciekiwaniuk/shop-system-backend:latest
                  command: ["cp", "-a",  "/var/www/.", "/app"]
                  volumeMounts:
                      - name: app-code
                        mountPath: /app
            volumes:
                -   name: app-code
                    emptyDir: { }
            containers:
                - name: backend
                  image: maciekiwaniuk/shop-system-backend:latest
                  ports:
                      - containerPort: 80
                        name: http
                  envFrom:
                      - configMapRef: { name: backend-config }
                      - secretRef:    { name: backend-secrets }
                  volumeMounts:
                      - name: app-code
                        mountPath: /var/www
                  livenessProbe:
                      httpGet:
                          path: /
                          port: 80
                      initialDelaySeconds: 30
                      periodSeconds: 10
                      timeoutSeconds: 5
                      failureThreshold: 3
                  readinessProbe:
                      httpGet:
                          path: /
                          port: 80
                      initialDelaySeconds: 20
                      periodSeconds: 5
                      timeoutSeconds: 3
                      failureThreshold: 3
