apiVersion: v1
kind: Service
metadata:
    name: backend
    namespace: shop-system
    labels:
        app.kubernetes.io/name: shop-system
        app.kubernetes.io/component: backend
        app.kubernetes.io/instance: local
spec:
    type: ClusterIP
    selector:
        app.kubernetes.io/component: backend
    ports:
        - name: http
          protocol: TCP
          port: 80
          targetPort: 80
